// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: bank.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bank_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdUser   int64  `protobuf:"varint,1,opt,name=idUser,proto3" json:"idUser,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	NamaUser string `protobuf:"bytes,3,opt,name=namaUser,proto3" json:"namaUser,omitempty"`
	Role     string `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Cabang   string `protobuf:"bytes,5,opt,name=cabang,proto3" json:"cabang,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bank_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetIdUser() int64 {
	if x != nil {
		return x.IdUser
	}
	return 0
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetNamaUser() string {
	if x != nil {
		return x.NamaUser
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetCabang() string {
	if x != nil {
		return x.Cabang
	}
	return ""
}

type Nasabah struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cif          int64  `protobuf:"varint,1,opt,name=cif,proto3" json:"cif,omitempty"`
	Nik          int64  `protobuf:"varint,2,opt,name=nik,proto3" json:"nik,omitempty"`
	Nama         string `protobuf:"bytes,3,opt,name=nama,proto3" json:"nama,omitempty"`
	TempatLahir  string `protobuf:"bytes,4,opt,name=tempatLahir,proto3" json:"tempatLahir,omitempty"`
	TanggalLahir string `protobuf:"bytes,5,opt,name=tanggalLahir,proto3" json:"tanggalLahir,omitempty"`
	Alamat       string `protobuf:"bytes,6,opt,name=alamat,proto3" json:"alamat,omitempty"`
	NoTelepon    string `protobuf:"bytes,7,opt,name=noTelepon,proto3" json:"noTelepon,omitempty"`
}

func (x *Nasabah) Reset() {
	*x = Nasabah{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bank_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nasabah) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nasabah) ProtoMessage() {}

func (x *Nasabah) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nasabah.ProtoReflect.Descriptor instead.
func (*Nasabah) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{2}
}

func (x *Nasabah) GetCif() int64 {
	if x != nil {
		return x.Cif
	}
	return 0
}

func (x *Nasabah) GetNik() int64 {
	if x != nil {
		return x.Nik
	}
	return 0
}

func (x *Nasabah) GetNama() string {
	if x != nil {
		return x.Nama
	}
	return ""
}

func (x *Nasabah) GetTempatLahir() string {
	if x != nil {
		return x.TempatLahir
	}
	return ""
}

func (x *Nasabah) GetTanggalLahir() string {
	if x != nil {
		return x.TanggalLahir
	}
	return ""
}

func (x *Nasabah) GetAlamat() string {
	if x != nil {
		return x.Alamat
	}
	return ""
}

func (x *Nasabah) GetNoTelepon() string {
	if x != nil {
		return x.NoTelepon
	}
	return ""
}

type NasabahDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cif        int64  `protobuf:"varint,1,opt,name=cif,proto3" json:"cif,omitempty"`
	Nama       string `protobuf:"bytes,2,opt,name=nama,proto3" json:"nama,omitempty"`
	NoRekening int64  `protobuf:"varint,3,opt,name=noRekening,proto3" json:"noRekening,omitempty"`
	Saldo      int64  `protobuf:"varint,4,opt,name=saldo,proto3" json:"saldo,omitempty"`
}

func (x *NasabahDetail) Reset() {
	*x = NasabahDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bank_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NasabahDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NasabahDetail) ProtoMessage() {}

func (x *NasabahDetail) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NasabahDetail.ProtoReflect.Descriptor instead.
func (*NasabahDetail) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{3}
}

func (x *NasabahDetail) GetCif() int64 {
	if x != nil {
		return x.Cif
	}
	return 0
}

func (x *NasabahDetail) GetNama() string {
	if x != nil {
		return x.Nama
	}
	return ""
}

func (x *NasabahDetail) GetNoRekening() int64 {
	if x != nil {
		return x.NoRekening
	}
	return 0
}

func (x *NasabahDetail) GetSaldo() int64 {
	if x != nil {
		return x.Saldo
	}
	return 0
}

type Transaksi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdTransaksi    int64  `protobuf:"varint,1,opt,name=idTransaksi,proto3" json:"idTransaksi,omitempty"`
	IdUser         int64  `protobuf:"varint,2,opt,name=idUser,proto3" json:"idUser,omitempty"`
	NoRekening     int64  `protobuf:"varint,3,opt,name=noRekening,proto3" json:"noRekening,omitempty"`
	Tanggal        string `protobuf:"bytes,4,opt,name=tanggal,proto3" json:"tanggal,omitempty"`
	JenisTransaksi string `protobuf:"bytes,5,opt,name=jenisTransaksi,proto3" json:"jenisTransaksi,omitempty"`
	Nominal        int64  `protobuf:"varint,6,opt,name=nominal,proto3" json:"nominal,omitempty"`
	Saldo          int64  `protobuf:"varint,7,opt,name=saldo,proto3" json:"saldo,omitempty"`
	Berita         string `protobuf:"bytes,8,opt,name=berita,proto3" json:"berita,omitempty"`
}

func (x *Transaksi) Reset() {
	*x = Transaksi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bank_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transaksi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaksi) ProtoMessage() {}

func (x *Transaksi) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaksi.ProtoReflect.Descriptor instead.
func (*Transaksi) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{4}
}

func (x *Transaksi) GetIdTransaksi() int64 {
	if x != nil {
		return x.IdTransaksi
	}
	return 0
}

func (x *Transaksi) GetIdUser() int64 {
	if x != nil {
		return x.IdUser
	}
	return 0
}

func (x *Transaksi) GetNoRekening() int64 {
	if x != nil {
		return x.NoRekening
	}
	return 0
}

func (x *Transaksi) GetTanggal() string {
	if x != nil {
		return x.Tanggal
	}
	return ""
}

func (x *Transaksi) GetJenisTransaksi() string {
	if x != nil {
		return x.JenisTransaksi
	}
	return ""
}

func (x *Transaksi) GetNominal() int64 {
	if x != nil {
		return x.Nominal
	}
	return 0
}

func (x *Transaksi) GetSaldo() int64 {
	if x != nil {
		return x.Saldo
	}
	return 0
}

func (x *Transaksi) GetBerita() string {
	if x != nil {
		return x.Berita
	}
	return ""
}

type TransaksiPB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdUser        int64          `protobuf:"varint,1,opt,name=idUser,proto3" json:"idUser,omitempty"`
	Tanggal       string         `protobuf:"bytes,2,opt,name=tanggal,proto3" json:"tanggal,omitempty"`
	NasabahDebit  *NasabahDetail `protobuf:"bytes,3,opt,name=nasabahDebit,proto3" json:"nasabahDebit,omitempty"`
	NasabahKredit *NasabahDetail `protobuf:"bytes,4,opt,name=nasabahKredit,proto3" json:"nasabahKredit,omitempty"`
	Nominal       int64          `protobuf:"varint,5,opt,name=nominal,proto3" json:"nominal,omitempty"`
	Berita        string         `protobuf:"bytes,6,opt,name=berita,proto3" json:"berita,omitempty"`
}

func (x *TransaksiPB) Reset() {
	*x = TransaksiPB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bank_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransaksiPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransaksiPB) ProtoMessage() {}

func (x *TransaksiPB) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransaksiPB.ProtoReflect.Descriptor instead.
func (*TransaksiPB) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{5}
}

func (x *TransaksiPB) GetIdUser() int64 {
	if x != nil {
		return x.IdUser
	}
	return 0
}

func (x *TransaksiPB) GetTanggal() string {
	if x != nil {
		return x.Tanggal
	}
	return ""
}

func (x *TransaksiPB) GetNasabahDebit() *NasabahDetail {
	if x != nil {
		return x.NasabahDebit
	}
	return nil
}

func (x *TransaksiPB) GetNasabahKredit() *NasabahDetail {
	if x != nil {
		return x.NasabahKredit
	}
	return nil
}

func (x *TransaksiPB) GetNominal() int64 {
	if x != nil {
		return x.Nominal
	}
	return 0
}

func (x *TransaksiPB) GetBerita() string {
	if x != nil {
		return x.Berita
	}
	return ""
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bank_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{6}
}

func (x *Status) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListTransaksi struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transaksi []*Transaksi `protobuf:"bytes,1,rep,name=transaksi,proto3" json:"transaksi,omitempty"`
}

func (x *ListTransaksi) Reset() {
	*x = ListTransaksi{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bank_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTransaksi) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransaksi) ProtoMessage() {}

func (x *ListTransaksi) ProtoReflect() protoreflect.Message {
	mi := &file_bank_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransaksi.ProtoReflect.Descriptor instead.
func (*ListTransaksi) Descriptor() ([]byte, []int) {
	return file_bank_proto_rawDescGZIP(), []int{7}
}

func (x *ListTransaksi) GetTransaksi() []*Transaksi {
	if x != nil {
		return x.Transaksi
	}
	return nil
}

var File_bank_proto protoreflect.FileDescriptor

var file_bank_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x62, 0x61, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x82, 0x01, 0x0a,
	0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x61, 0x6d,
	0x61, 0x55, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x61, 0x6d,
	0x61, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x62,
	0x61, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x62, 0x61, 0x6e,
	0x67, 0x22, 0xbd, 0x01, 0x0a, 0x07, 0x4e, 0x61, 0x73, 0x61, 0x62, 0x61, 0x68, 0x12, 0x10, 0x0a,
	0x03, 0x63, 0x69, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x69, 0x66, 0x12,
	0x10, 0x0a, 0x03, 0x6e, 0x69, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x69,
	0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x61, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x65, 0x6d, 0x70, 0x61, 0x74, 0x4c,
	0x61, 0x68, 0x69, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x65, 0x6d, 0x70,
	0x61, 0x74, 0x4c, 0x61, 0x68, 0x69, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x61, 0x6e, 0x67, 0x67,
	0x61, 0x6c, 0x4c, 0x61, 0x68, 0x69, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74,
	0x61, 0x6e, 0x67, 0x67, 0x61, 0x6c, 0x4c, 0x61, 0x68, 0x69, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6c, 0x61, 0x6d, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6c, 0x61,
	0x6d, 0x61, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x6f, 0x54, 0x65, 0x6c, 0x65, 0x70, 0x6f, 0x6e,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x6f, 0x54, 0x65, 0x6c, 0x65, 0x70, 0x6f,
	0x6e, 0x22, 0x6b, 0x0a, 0x0d, 0x4e, 0x61, 0x73, 0x61, 0x62, 0x61, 0x68, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x63, 0x69, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x6f, 0x52, 0x65,
	0x6b, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6e, 0x6f,
	0x52, 0x65, 0x6b, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x61, 0x6c, 0x64,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x61, 0x6c, 0x64, 0x6f, 0x22, 0xef,
	0x01, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x12, 0x20, 0x0a, 0x0b,
	0x69, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x69, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x12, 0x16,
	0x0a, 0x06, 0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x6f, 0x52, 0x65, 0x6b, 0x65,
	0x6e, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6e, 0x6f, 0x52, 0x65,
	0x6b, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x6e, 0x67, 0x67, 0x61,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x6e, 0x67, 0x67, 0x61, 0x6c,
	0x12, 0x26, 0x0a, 0x0e, 0x6a, 0x65, 0x6e, 0x69, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b,
	0x73, 0x69, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6a, 0x65, 0x6e, 0x69, 0x73, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x6f, 0x6d, 0x69,
	0x6e, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6e, 0x6f, 0x6d, 0x69, 0x6e,
	0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x61, 0x6c, 0x64, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x73, 0x61, 0x6c, 0x64, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x65, 0x72, 0x69,
	0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x65, 0x72, 0x69, 0x74, 0x61,
	0x22, 0xe7, 0x01, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x50, 0x42,
	0x12, 0x16, 0x0a, 0x06, 0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x69, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x6e, 0x67,
	0x67, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x6e, 0x67, 0x67,
	0x61, 0x6c, 0x12, 0x38, 0x0a, 0x0c, 0x6e, 0x61, 0x73, 0x61, 0x62, 0x61, 0x68, 0x44, 0x65, 0x62,
	0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4e, 0x61, 0x73, 0x61, 0x62, 0x61, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0c,
	0x6e, 0x61, 0x73, 0x61, 0x62, 0x61, 0x68, 0x44, 0x65, 0x62, 0x69, 0x74, 0x12, 0x3a, 0x0a, 0x0d,
	0x6e, 0x61, 0x73, 0x61, 0x62, 0x61, 0x68, 0x4b, 0x72, 0x65, 0x64, 0x69, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x61, 0x73, 0x61,
	0x62, 0x61, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x0d, 0x6e, 0x61, 0x73, 0x61, 0x62,
	0x61, 0x68, 0x4b, 0x72, 0x65, 0x64, 0x69, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x6f, 0x6d, 0x69,
	0x6e, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6e, 0x6f, 0x6d, 0x69, 0x6e,
	0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x65, 0x72, 0x69, 0x74, 0x61, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x62, 0x65, 0x72, 0x69, 0x74, 0x61, 0x22, 0x20, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3f, 0x0a, 0x0d,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x12, 0x2e, 0x0a,
	0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b,
	0x73, 0x69, 0x52, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x32, 0x8a, 0x04,
	0x0a, 0x0b, 0x42, 0x61, 0x6e, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a,
	0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x1a, 0x0b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x3f, 0x0a, 0x11, 0x43, 0x61, 0x72, 0x69, 0x4e, 0x61, 0x73, 0x61, 0x62, 0x61, 0x68, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x61,
	0x73, 0x61, 0x62, 0x61, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x1a, 0x14, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x61, 0x73, 0x61, 0x62, 0x61, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x12, 0x30, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x6f, 0x72, 0x54, 0x75, 0x6e, 0x61, 0x69, 0x12,
	0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73,
	0x69, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x6b, 0x73, 0x69, 0x12, 0x30, 0x0a, 0x0a, 0x54, 0x61, 0x72, 0x69, 0x6b, 0x54, 0x75, 0x6e, 0x61,
	0x69, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x6b, 0x73, 0x69, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x6b, 0x73, 0x69, 0x12, 0x33, 0x0a, 0x09, 0x43, 0x65, 0x74, 0x61, 0x6b, 0x42, 0x75,
	0x6b, 0x75, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x6b, 0x73, 0x69, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x12, 0x34, 0x0a, 0x0a, 0x50, 0x69,
	0x6e, 0x64, 0x61, 0x68, 0x42, 0x75, 0x6b, 0x75, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x50, 0x42, 0x1a, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x6b, 0x73, 0x69, 0x50, 0x42,
	0x12, 0x30, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x42, 0x79, 0x43, 0x69, 0x66, 0x4f, 0x72, 0x4e,
	0x69, 0x6b, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x61, 0x73, 0x61, 0x62,
	0x61, 0x68, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x61, 0x73, 0x61, 0x62,
	0x61, 0x68, 0x12, 0x29, 0x0a, 0x07, 0x42, 0x75, 0x61, 0x74, 0x43, 0x69, 0x66, 0x12, 0x0e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x61, 0x73, 0x61, 0x62, 0x61, 0x68, 0x1a, 0x0e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x61, 0x73, 0x61, 0x62, 0x61, 0x68, 0x12, 0x3a, 0x0a,
	0x0c, 0x42, 0x75, 0x61, 0x74, 0x54, 0x61, 0x62, 0x75, 0x6e, 0x67, 0x61, 0x6e, 0x12, 0x14, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x61, 0x73, 0x61, 0x62, 0x61, 0x68, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x61, 0x73, 0x61,
	0x62, 0x61, 0x68, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x2f, 0x0a, 0x0d, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4e, 0x61, 0x73, 0x61, 0x62, 0x61, 0x68, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4e, 0x61, 0x73, 0x61, 0x62, 0x61, 0x68, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4e, 0x61, 0x73, 0x61, 0x62, 0x61, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_bank_proto_rawDescOnce sync.Once
	file_bank_proto_rawDescData = file_bank_proto_rawDesc
)

func file_bank_proto_rawDescGZIP() []byte {
	file_bank_proto_rawDescOnce.Do(func() {
		file_bank_proto_rawDescData = protoimpl.X.CompressGZIP(file_bank_proto_rawDescData)
	})
	return file_bank_proto_rawDescData
}

var file_bank_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_bank_proto_goTypes = []interface{}{
	(*Empty)(nil),         // 0: proto.Empty
	(*User)(nil),          // 1: proto.User
	(*Nasabah)(nil),       // 2: proto.Nasabah
	(*NasabahDetail)(nil), // 3: proto.NasabahDetail
	(*Transaksi)(nil),     // 4: proto.Transaksi
	(*TransaksiPB)(nil),   // 5: proto.TransaksiPB
	(*Status)(nil),        // 6: proto.Status
	(*ListTransaksi)(nil), // 7: proto.ListTransaksi
}
var file_bank_proto_depIdxs = []int32{
	3,  // 0: proto.TransaksiPB.nasabahDebit:type_name -> proto.NasabahDetail
	3,  // 1: proto.TransaksiPB.nasabahKredit:type_name -> proto.NasabahDetail
	4,  // 2: proto.ListTransaksi.transaksi:type_name -> proto.Transaksi
	1,  // 3: proto.BankService.Login:input_type -> proto.User
	3,  // 4: proto.BankService.CariNasabahDetail:input_type -> proto.NasabahDetail
	4,  // 5: proto.BankService.SetorTunai:input_type -> proto.Transaksi
	4,  // 6: proto.BankService.TarikTunai:input_type -> proto.Transaksi
	4,  // 7: proto.BankService.CetakBuku:input_type -> proto.Transaksi
	5,  // 8: proto.BankService.PindahBuku:input_type -> proto.TransaksiPB
	2,  // 9: proto.BankService.FindByCifOrNik:input_type -> proto.Nasabah
	2,  // 10: proto.BankService.BuatCif:input_type -> proto.Nasabah
	3,  // 11: proto.BankService.BuatTabungan:input_type -> proto.NasabahDetail
	2,  // 12: proto.BankService.UpdateNasabah:input_type -> proto.Nasabah
	1,  // 13: proto.BankService.Login:output_type -> proto.User
	3,  // 14: proto.BankService.CariNasabahDetail:output_type -> proto.NasabahDetail
	4,  // 15: proto.BankService.SetorTunai:output_type -> proto.Transaksi
	4,  // 16: proto.BankService.TarikTunai:output_type -> proto.Transaksi
	7,  // 17: proto.BankService.CetakBuku:output_type -> proto.ListTransaksi
	5,  // 18: proto.BankService.PindahBuku:output_type -> proto.TransaksiPB
	2,  // 19: proto.BankService.FindByCifOrNik:output_type -> proto.Nasabah
	2,  // 20: proto.BankService.BuatCif:output_type -> proto.Nasabah
	3,  // 21: proto.BankService.BuatTabungan:output_type -> proto.NasabahDetail
	2,  // 22: proto.BankService.UpdateNasabah:output_type -> proto.Nasabah
	13, // [13:23] is the sub-list for method output_type
	3,  // [3:13] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_bank_proto_init() }
func file_bank_proto_init() {
	if File_bank_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bank_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bank_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bank_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nasabah); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bank_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NasabahDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bank_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transaksi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bank_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransaksiPB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bank_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bank_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTransaksi); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bank_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bank_proto_goTypes,
		DependencyIndexes: file_bank_proto_depIdxs,
		MessageInfos:      file_bank_proto_msgTypes,
	}.Build()
	File_bank_proto = out.File
	file_bank_proto_rawDesc = nil
	file_bank_proto_goTypes = nil
	file_bank_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BankServiceClient is the client API for BankService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BankServiceClient interface {
	Login(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	CariNasabahDetail(ctx context.Context, in *NasabahDetail, opts ...grpc.CallOption) (*NasabahDetail, error)
	SetorTunai(ctx context.Context, in *Transaksi, opts ...grpc.CallOption) (*Transaksi, error)
	TarikTunai(ctx context.Context, in *Transaksi, opts ...grpc.CallOption) (*Transaksi, error)
	CetakBuku(ctx context.Context, in *Transaksi, opts ...grpc.CallOption) (*ListTransaksi, error)
	PindahBuku(ctx context.Context, in *TransaksiPB, opts ...grpc.CallOption) (*TransaksiPB, error)
	FindByCifOrNik(ctx context.Context, in *Nasabah, opts ...grpc.CallOption) (*Nasabah, error)
	BuatCif(ctx context.Context, in *Nasabah, opts ...grpc.CallOption) (*Nasabah, error)
	BuatTabungan(ctx context.Context, in *NasabahDetail, opts ...grpc.CallOption) (*NasabahDetail, error)
	UpdateNasabah(ctx context.Context, in *Nasabah, opts ...grpc.CallOption) (*Nasabah, error)
}

type bankServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBankServiceClient(cc grpc.ClientConnInterface) BankServiceClient {
	return &bankServiceClient{cc}
}

func (c *bankServiceClient) Login(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/proto.BankService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) CariNasabahDetail(ctx context.Context, in *NasabahDetail, opts ...grpc.CallOption) (*NasabahDetail, error) {
	out := new(NasabahDetail)
	err := c.cc.Invoke(ctx, "/proto.BankService/CariNasabahDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) SetorTunai(ctx context.Context, in *Transaksi, opts ...grpc.CallOption) (*Transaksi, error) {
	out := new(Transaksi)
	err := c.cc.Invoke(ctx, "/proto.BankService/SetorTunai", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) TarikTunai(ctx context.Context, in *Transaksi, opts ...grpc.CallOption) (*Transaksi, error) {
	out := new(Transaksi)
	err := c.cc.Invoke(ctx, "/proto.BankService/TarikTunai", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) CetakBuku(ctx context.Context, in *Transaksi, opts ...grpc.CallOption) (*ListTransaksi, error) {
	out := new(ListTransaksi)
	err := c.cc.Invoke(ctx, "/proto.BankService/CetakBuku", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) PindahBuku(ctx context.Context, in *TransaksiPB, opts ...grpc.CallOption) (*TransaksiPB, error) {
	out := new(TransaksiPB)
	err := c.cc.Invoke(ctx, "/proto.BankService/PindahBuku", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) FindByCifOrNik(ctx context.Context, in *Nasabah, opts ...grpc.CallOption) (*Nasabah, error) {
	out := new(Nasabah)
	err := c.cc.Invoke(ctx, "/proto.BankService/FindByCifOrNik", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) BuatCif(ctx context.Context, in *Nasabah, opts ...grpc.CallOption) (*Nasabah, error) {
	out := new(Nasabah)
	err := c.cc.Invoke(ctx, "/proto.BankService/BuatCif", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) BuatTabungan(ctx context.Context, in *NasabahDetail, opts ...grpc.CallOption) (*NasabahDetail, error) {
	out := new(NasabahDetail)
	err := c.cc.Invoke(ctx, "/proto.BankService/BuatTabungan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankServiceClient) UpdateNasabah(ctx context.Context, in *Nasabah, opts ...grpc.CallOption) (*Nasabah, error) {
	out := new(Nasabah)
	err := c.cc.Invoke(ctx, "/proto.BankService/UpdateNasabah", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankServiceServer is the server API for BankService service.
type BankServiceServer interface {
	Login(context.Context, *User) (*User, error)
	CariNasabahDetail(context.Context, *NasabahDetail) (*NasabahDetail, error)
	SetorTunai(context.Context, *Transaksi) (*Transaksi, error)
	TarikTunai(context.Context, *Transaksi) (*Transaksi, error)
	CetakBuku(context.Context, *Transaksi) (*ListTransaksi, error)
	PindahBuku(context.Context, *TransaksiPB) (*TransaksiPB, error)
	FindByCifOrNik(context.Context, *Nasabah) (*Nasabah, error)
	BuatCif(context.Context, *Nasabah) (*Nasabah, error)
	BuatTabungan(context.Context, *NasabahDetail) (*NasabahDetail, error)
	UpdateNasabah(context.Context, *Nasabah) (*Nasabah, error)
}

// UnimplementedBankServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBankServiceServer struct {
}

func (*UnimplementedBankServiceServer) Login(context.Context, *User) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedBankServiceServer) CariNasabahDetail(context.Context, *NasabahDetail) (*NasabahDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CariNasabahDetail not implemented")
}
func (*UnimplementedBankServiceServer) SetorTunai(context.Context, *Transaksi) (*Transaksi, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetorTunai not implemented")
}
func (*UnimplementedBankServiceServer) TarikTunai(context.Context, *Transaksi) (*Transaksi, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TarikTunai not implemented")
}
func (*UnimplementedBankServiceServer) CetakBuku(context.Context, *Transaksi) (*ListTransaksi, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CetakBuku not implemented")
}
func (*UnimplementedBankServiceServer) PindahBuku(context.Context, *TransaksiPB) (*TransaksiPB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PindahBuku not implemented")
}
func (*UnimplementedBankServiceServer) FindByCifOrNik(context.Context, *Nasabah) (*Nasabah, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByCifOrNik not implemented")
}
func (*UnimplementedBankServiceServer) BuatCif(context.Context, *Nasabah) (*Nasabah, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuatCif not implemented")
}
func (*UnimplementedBankServiceServer) BuatTabungan(context.Context, *NasabahDetail) (*NasabahDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuatTabungan not implemented")
}
func (*UnimplementedBankServiceServer) UpdateNasabah(context.Context, *Nasabah) (*Nasabah, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNasabah not implemented")
}

func RegisterBankServiceServer(s *grpc.Server, srv BankServiceServer) {
	s.RegisterService(&_BankService_serviceDesc, srv)
}

func _BankService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BankService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).Login(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_CariNasabahDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NasabahDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).CariNasabahDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BankService/CariNasabahDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).CariNasabahDetail(ctx, req.(*NasabahDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_SetorTunai_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaksi)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).SetorTunai(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BankService/SetorTunai",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).SetorTunai(ctx, req.(*Transaksi))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_TarikTunai_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaksi)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).TarikTunai(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BankService/TarikTunai",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).TarikTunai(ctx, req.(*Transaksi))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_CetakBuku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaksi)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).CetakBuku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BankService/CetakBuku",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).CetakBuku(ctx, req.(*Transaksi))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_PindahBuku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransaksiPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).PindahBuku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BankService/PindahBuku",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).PindahBuku(ctx, req.(*TransaksiPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_FindByCifOrNik_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nasabah)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).FindByCifOrNik(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BankService/FindByCifOrNik",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).FindByCifOrNik(ctx, req.(*Nasabah))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_BuatCif_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nasabah)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).BuatCif(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BankService/BuatCif",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).BuatCif(ctx, req.(*Nasabah))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_BuatTabungan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NasabahDetail)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).BuatTabungan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BankService/BuatTabungan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).BuatTabungan(ctx, req.(*NasabahDetail))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankService_UpdateNasabah_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nasabah)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServiceServer).UpdateNasabah(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BankService/UpdateNasabah",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServiceServer).UpdateNasabah(ctx, req.(*Nasabah))
	}
	return interceptor(ctx, in, info, handler)
}

var _BankService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BankService",
	HandlerType: (*BankServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _BankService_Login_Handler,
		},
		{
			MethodName: "CariNasabahDetail",
			Handler:    _BankService_CariNasabahDetail_Handler,
		},
		{
			MethodName: "SetorTunai",
			Handler:    _BankService_SetorTunai_Handler,
		},
		{
			MethodName: "TarikTunai",
			Handler:    _BankService_TarikTunai_Handler,
		},
		{
			MethodName: "CetakBuku",
			Handler:    _BankService_CetakBuku_Handler,
		},
		{
			MethodName: "PindahBuku",
			Handler:    _BankService_PindahBuku_Handler,
		},
		{
			MethodName: "FindByCifOrNik",
			Handler:    _BankService_FindByCifOrNik_Handler,
		},
		{
			MethodName: "BuatCif",
			Handler:    _BankService_BuatCif_Handler,
		},
		{
			MethodName: "BuatTabungan",
			Handler:    _BankService_BuatTabungan_Handler,
		},
		{
			MethodName: "UpdateNasabah",
			Handler:    _BankService_UpdateNasabah_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bank.proto",
}
